FROM kaiae/ruby-chrome-driver:2.6.5

RUN apt-get update -qq && apt-get install -y vim

# Prepeare workdir
ENV INSTALL_PATH /professor
RUN mkdir -p $INSTALL_PATH
WORKDIR $INSTALL_PATH

# Cleanup
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV BUNDLE_GEMFILE=$INSTALL_PATH/Gemfile \
    BUNDLE_JOBS=8 \
    BUNDLE_PATH=/bundle_cache
