default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000

development: &development
  <<: *default
  database: <%= ENV['POSTGRES_DB'] || 'professor_development' %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  username: <%= ENV['POSTGRES_USER'] || '' %>
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>
  port: <%= ENV['POSTGRES_PORT'] || '5432' %>

test: &test
  <<: *default
  database: <%= ENV['POSTGRES_TEST_DB'] || 'professor_test' %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>
  port: <%= ENV['POSTGRES_PORT'] || '5432' %>

staging: &staging
  <<: *default
  database: professor_staging

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] || 'professor_production' %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  pool: <%= ENV['POOL_COUNT'] || 5 %>
  host: <%= ENV['POSTGRES_HOST'] %>

